apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-at13
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-at13
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-at13
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-at13
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-at13
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ftoo-tenant/rhtap-demo-app/hacbs-test-project-at13@sha256:5219e4f5801b044b546751e96927f3ff39d9ff2eef0263404f6441ff3891e7a8
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
